### ISSUE TITLE
revert.Case

### ISSUE THREAD

**Issue by VasylUlianovskyi** [dosandk/online-editor-tasks#11]
Володимир, в мене питання чому тут revertCase('Hello World') в дужках вказано значення стрічки а в solution ті самі дужки пусті?

**Comment by dosandk** [comment]
@VasylUlianovskyi а можно більше деталей, про які саме пусті дужки в `solution` іде мова?

**Comment by VasylUlianovskyi** [comment]
> @VasylUlianovskyi а можно більше деталей, про які саме пусті дужки в `solution` іде мова?

export const revertCase = (string = '') => {
  let result = '';

  for (const char of string) {
    if (char === char.toUpperCase()) {
      result += char.toLowerCase();
    } else {
      result += char.toUpperCase();
    }
  }

  return result;
}



В прикладі було так 
revertCase('Hello World'); // hELLO wORLD

мабуть або до кінця не розібрався, або щось не так зрозумів

**Comment by dosandk** [comment]
@VasylUlianovskyi `string` - це ім'я змінної, по замовченню має значення порожної стрічки:
```
export const revertCase = (string = '') => { ...
```

але коли ми викликаємо функцію, ми передаємо то значення яке хочемо перетворити за допомогою цієї функції:

```
revertCase('foo bar bar'); // FOO BAR BAZ
```
