### ISSUE TITLE
sumArrayElements

### ISSUE THREAD

**Issue by volodymyr35** [dosandk/online-editor-tasks#15]
При спробі запустити тести, виводиться TypeError.

![TypeError](https://user-images.githubusercontent.com/34597781/169596087-8ef9aba6-2d25-4c84-9867-9815ab71bdd1.png)

**Comment by dosandk** [comment]
@volodymyr35 А де код який призводить до цих помилок?
Додайте його до issue

**Comment by volodymyr35** [comment]
Я вже вирішив його, дякую!
