### ISSUE TITLE
highestAndLowest

### ISSUE THREAD

**Issue by YuriyVoitykhivskyi** [dosandk/online-editor-tasks#16]
1. Переходимо в завдання highestAndLowest
2. Виконуємо завдання, і тут є одна особливість. Якщо ми стрічку 'numbers' будемо розділяти комою в методі (.split), то після компіляції  буде видано, що завдання не вирішено, хоча вивід в консоль правильний.

![Screenshot_1](https://user-images.githubusercontent.com/66677219/169655770-e99e72f3-8b89-486e-b70a-c1a1d4b2f471.png)

**Comment by dosandk** [comment]
@YuriyVoitykhivskyi будь ласка перевірте файл тестів. Ви побачете, що в тестах, як і в описі завдання, в стрічці числа розбите НЕ комою, а пробілом. Це вимога завдання.
