### ISSUE TITLE
pick

### ISSUE THREAD

**Issue by OlhaSoroka** [dosandk/online-editor-tasks#4]
Online editor breaks,laggs and doesn't show any info in block "Test" when I put down my solution.

1. Go to 'http://online-editor.bootcamp.place/pick'
2. Go to "index.js"
3. Put down my solution : 
let object = {};
  for (const item of fields) {
    object[item] = obj[item];
  }

  return object;

4.Press button "Run"
5. See error

Expected behavior
Online editor show notification about successfull or unsuccessfull pass of task.

![image](https://user-images.githubusercontent.com/94988071/166909797-6c6c1291-fdf2-44b6-9c71-2f6a806d4865.png)

**Desktop (please complete the following information):**
 - Chrome
 - Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by OlhaSoroka** [comment]
I change my solution, and now everything work fine, but if solution is wrong we still have this issue;
![image](https://user-images.githubusercontent.com/94988071/167079074-7732a567-4d17-42c5-a8dc-ed5ee6b81f69.png)

**Comment by dosandk** [comment]
@OlhaSoroka thanks for the bug report. The problem was fixed. 
Your previous solution should not break the application but does not satisfy two tests:
* should return an empty object if the passed field does not found
* should return only own object properties

```js
let object = {};

for (const item of fields) {
  object[item] = obj[item];
}

return object;
```
