### ISSUE TITLE
arrToString

### ISSUE THREAD

**Issue by ludamiheeva1988** [dosandk/online-editor-tasks#6]
Завдання виглядає так:
Необхідно реалізувати функцію arrToString, яка приймає в **_якості аргументу масив_**, а повертає всі елементи масиву об'єднані в стрічку.
А в рішенні в якості аргумента приймається стрічка.  Тест на уважність.

export const arrToString = **_(arr = '',_** delimiter = '') => {

};
В завдан
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dosandk** [comment]
@ludamiheeva1988 Виправлено, дякую!
