### ISSUE TITLE
revertCase

### ISSUE THREAD

**Issue by nosovandriy** [dosandk/online-editor-tasks#7]
Такий варіант розв'язку також би мало пропускати.
![image](https://user-images.githubusercontent.com/55395284/167442948-d4df9787-e6e8-4eb1-b057-ec8a697f03ba.png)

**Comment by dosandk** [comment]
@nosovandriy A чи враховує Ваше рішення обробку пробільного символу?
Що буде якщо викликати данну реалізацію з ось такою стрічкою: `Hello World!`?
